<?php

namespace AppBundle\Repository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTeamByName($team)
    {
        $dql = "SELECT t FROM AppBundle:Team t WHERE t.name = :team";
        return $this->getEntityManager()->createQuery($dql)->setParameter('team', $team)->getOneOrNullResult();
    }
}
